### ISSUE TITLE
Comments on TpFactory.py

### ISSUE THREAD

**Issue by beckyc567** [richClubb/python-uds#17]
TpFactory.py

- does the class only ever have a single static method? (other than what's inherited from object)

- line 48: calling a static method "create" which doesn't appear anywhere? - a mistake or something in python I've not seen before? Looks like it should be calling "tpFactory('CAN')"?

- otherwise looks OK

**Comment by richClubb** [comment]
Good review. I will have to revise the factory method as I'm not fully sure I'm actually implementing factories

**Comment by richClubb** [comment]
refactored the class to use the __call__ method for creating the actual instances. I think this provides a nicer interface.
