### ISSUE TITLE
Comments on CanTpListener.py

### ISSUE THREAD

**Issue by beckyc567** [richClubb/python-uds#20]
CanTpListener.py

- line 16: "may want to be" ... looks like it now is

- line 32: an alternative would be to undefine "on_message_received()", e.g. "   del self.on_message_received" - in practise both give a TypeError, but you'll get a different error message - the code is fine, but just in case you weren't aware of how to undefine things (the latter releases resources, whereas the former will hang on to the "None" and stuff.  ... assuming of course that I've remembered correctly!

- otherwise looks OK

**Comment by richClubb** [comment]
The CanTpListener class has been removed for the time being, this is for the V.0.1 release as it was not necessary.
It is a good idea to have this as it might help to decouple the CanTp class from the python-can implementation which is desirable if other interfaces are required at a later stage. But for the time being this is not going to be addressed
