### ISSUE TITLE
Comments on CanTp.py

### ISSUE THREAD

**Issue by beckyc567** [richClubb/python-uds#21]
CanTp.py

- for the condition on line 125 to make sense after line 121, presumably one of the above flows can update the state to END_OF_BLOCK - seems likely but just checking, and it may be worth a comment? ... if you can add one at line 70, then you can add one here

- other than usual comments, it otherwise looks good.

**Comment by richClubb** [comment]
CanTp has some larger deficiencies and the CanTp and CanTpMessage structure seems to be a bad choice.

This needs to be fully re-factored to get rid of the CanTpMessage interaction and use a single CanTp class

**Comment by richClubb** [comment]
CanTp has been heavily refactored and this comment is no longer valid. May need a re-assessment
