### ISSUE TITLE
"self" used in static methods can be confusing

### ISSUE THREAD

**Issue by beckyc567** [richClubb/python-uds#9]
In UdsConfigTool.py, in "def readDataByIdentifier(self,diagnosticIdentifier)" ...
use of "self" like this in a non-class function can be a little confusing
... but I appreciate this is in the "experiments"
It's also light on comments describe what is happening here, but I know what it's doing. "target" may be a better parameter name than "self" in this context?

**Comment by richClubb** [comment]
self keyword changed to target to make this clearer
